### ISSUE TITLE
Why the training makes no efforts?

### ISSUE THREAD

**Issue by ailias** [hizhangp/yolo_tensorflow#18]
Dear all:
    I have been training this network thousands of iterations, but I nearly cannot find any change about the loss value. So what's wrong? Does anyone have validated its validity?
![yolo](https://cloud.githubusercontent.com/assets/10510469/26229000/ef536b98-3c70-11e7-9ca2-1e00365baa79.jpg)
![yolo2](https://cloud.githubusercontent.com/assets/10510469/26229002/f39afff4-3c70-11e7-87ff-8ff4f8121488.jpg)

**Comment by ericdoerheit** [comment]
Have you used a pre-trained network or where you training from scratch? In the original paper it is described, that they train the first CNN layers for solving a classification task, e. g. based on the ImageNet dataset and then add some more layers and fine-tune for object detection. [Section 2.2, https://arxiv.org/abs/1506.02640] I am not sure whether this is the reason for the problem, but maybe you could try to train with pre-trained weights?

**Comment by joashchn** [comment]
@ailias 
i have the seem question ,i changed the input data code(only train 'car' and 'cat'),but after the trainning,nothing can be detected
i did not use any pre-trained weights, and here i have another question,if the class i want to train is not in the pre-trained weights,can i use the pre-train weights?

**Comment by jongsukchoi** [comment]
@joashchn 
hi joashchn 
i have same problem with you. 
did you solve the this problem?
my goal is the just one object detection in image. 
perhaps, your goal is the two object detection in image.

**Comment by liuhyCV** [comment]
@joashchn @ailias did you solve the problem? I have train it and test nothing in cat.jpg or person.jpg. Its training problem?

**Comment by feitiandemiaomi** [comment]
@liuhyCV  Did you meet the question of testing noting in person.jpg ? Just like  the original jpg ,did not have any output and circle ， did you solve the problem?

**Comment by shadowdyj** [comment]
I have the problem when I train the model without pre-training. The total loss goes from 42 to 10, and cannot get less any more. However I get loss about 6 when I fine-turn the model using the Yolo_small.ckpt .
Is it impossible to train the model without any pre-trained weight?

**Comment by linydf** [comment]
I also meet the same question. I train the download model-YOLO-small ,but finally,I find the result is pretty worse,i set the iteration time is thirty thousands.

**Comment by ss199302** [comment]
Has anyone solved the problem of non training?

**Comment by ss199302** [comment]
Has anyone solved the problem of training?

**Comment by liuyicheng007** [comment]
I have the same problems with you. I thought the weight that I trained without pre-training was not good that cause the problem（detect nothing）.Then I changed the  parameter‘THRESHOLD ’（in the config file） to 0.01，it did work！Although the result was not right！So my conclusion is if our loss can arrive about 6，the weight can be good enough to detect !

**Comment by ss199302** [comment]
@ailias  Have you solved the problem of training?

**Comment by linydf** [comment]
now my loss arrive 3.    but I am failed to result this condition

**Comment by ss199302** [comment]
@linydf  What data set do you use?thanks！

**Comment by xiaoshuguo750** [comment]
@joashchn  @jongsukchoi 
Hi!
How can I changed the code if I want to input data (only train 'car' and 'cat')?
Thank you!
Shu Guo

**Comment by zy486at189cn** [comment]
edit config.py,just as this:

#WEIGHTS_FILE = None
WEIGHTS_FILE = os.path.join(DATA_PATH, 'weights', 'YOLO_small.ckpt')

when turn on  the pre-training weights YOLO_small.ckpt，the trained model can make effect!

my test.py which use the trained model ,just like this:

class Detector(object):

    def __init__(self, net, weight_file):
        self.net = net
        self.weights_file = weight_file

        self.classes = cfg.CLASSES
        self.num_class = len(self.classes)
        self.image_size = cfg.IMAGE_SIZE
        self.cell_size = cfg.CELL_SIZE
        self.boxes_per_cell = cfg.BOXES_PER_CELL
        self.threshold = cfg.THRESHOLD
        self.iou_threshold = cfg.IOU_THRESHOLD
        self.boundary1 = self.cell_size * self.cell_size * self.num_class
        self.boundary2 = self.boundary1 + self.cell_size * self.cell_size * self.boxes_per_cell

        self.sess = tf.Session()
        self.sess.run(tf.global_variables_initializer())
             
        PATH = **'/media/stockerc/f/wz/project/yolo/data/pascal_voc/output/2018_02_23_11_13'
        print 'Restoring weights from: ' + PATH
        self.saver = tf.train.Saver()
        ckpt = tf.train.get_checkpoint_state(PATH)
        self.saver.restore(self.sess, ckpt.model_checkpoint_path)

**Comment by leadcain84** [comment]
How do you get the 'YOLO_small.ckpt you gave'?
is it your training results? or others.

**Comment by zy486at189cn** [comment]
I download it
   
   
   -- 发自189邮箱 App
   点击下载，安全、高效管理邮箱
   
  http://t.mail.189.cn/rcyyzhw 
  
  
  
   leadcain84 <notifications@github.com>写到：
    
    How do you get the 'YOLO_small.ckpt you gave'? is it your training results? or others.

**Comment by MindyZLM** [comment]
@joashchn  i have same problem with you.
did you solve the this problem?

**Comment by XiangqianMa** [comment]
My model can get the loss of 3, but it can not detect any right objects. Before i trained this model to fine-tune my own data, i have tried to fine-tune this model on pascal-voc, it can detect the right objects, but it's confidence was  very low, such as 0.6.

**Comment by M000M** [comment]
I have the same problem. I doubt that the model is right, but there's some errors in the loss function.

**Comment by guker** [comment]
I have the same problem, do you solve it?

**Comment by guker** [comment]
> Have you used a pre-trained network or where you training from scratch? In the original paper it is described, that they train the first CNN layers for solving a classification task, e. g. based on the ImageNet dataset and then add some more layers and fine-tune for object detection. [Section 2.2, https://arxiv.org/abs/1506.02640] I am not sure whether this is the reason for the problem, but maybe you could try to train with pre-trained weights?

yes， you must pretrain，not train from scrath，otherwise，loss is about 10.0 and does not decrease

**Comment by LinzzMichael** [comment]
> > Have you used a pre-trained network or where you training from scratch? In the original paper it is described, that they train the first CNN layers for solving a classification task, e. g. based on the ImageNet dataset and then add some more layers and fine-tune for object detection. [Section 2.2, https://arxiv.org/abs/1506.02640] I am not sure whether this is the reason for the problem, but maybe you could try to train with pre-trained weights?
> 
> yes， you must pretrain，not train from scrath，otherwise，loss is about 10.0 and does not decrease

@guker I have some problem,if my the num of detect classes is 5 not 20,how can I pre train,can I pre train with the YOLO_small.ckpt,or I need to pre train with only 5 classes?

**Comment by fgyong** [comment]
Dear All, I follow the ReadMe steps to run train.py but an error occured as follow:
> Traceback (most recent call last):
  File "train.py", line 164, in <module>
    main()
  File "train.py", line 157, in main
    solver.train()
  File "train.py", line 90, in train
    train_timer.remain(step, self.max_iter))
ValueError: Unknown format code 'f' for object of type 'str'

if anybody have the same problem when running train.py, please tell me how to solve it. Thank you guys!
