### ISSUE TITLE
issue, I am wondering about following one

### ISSUE THREAD

**Issue by jk5500** [hizhangp/yolo_tensorflow#68]
Traceback (most recent call last):
  File "train.py", line 164, in <module>
    main()
  File "train.py", line 157, in main
    solver.train()
  File "train.py", line 90, in train
    train_timer.remain(step, self.max_iter))
ValueError: Unknown format code 'f' for object of type 'str'

**Comment by Meghal17** [comment]
I am having the same problem, need some help!

**Comment by jk5500** [comment]
Hopefully, You may not get this issue in python 2. In pythton string byte works slightly different.
You need to look at that line change to python 3 for str conversion of jpg

**Comment by seriouslym** [comment]
Do you solve the problem?
I have no idea for the same problem .

**Comment by aidevveloper** [comment]
Do you solve the problem?

**Comment by Xpangz** [comment]
I delete the ':3f' in {} of log_str, and it works  :>
